### ISSUE TITLE
Line 313

### ISSUE THREAD

**Issue by xHN35RQ** [titoBouzout/Open-Include#68] opened 2015-04-21 05:06 UTC
Should not [Line 313](https://github.com/titoBouzout/Open-Include/blob/555daefa/open_include.py#L313) be something like the following?

`paths = re.sub('"|\'|<|>|\(|\)|\{|\}\[|\]', '', paths)`

I wonder if I missed this line when I submitted #65

**Comment by titoBouzout** [comment] 2015-04-21 10:43
can you please explain the reasons behind your reasoning, what changes?
thanks

**Comment by xHN35RQ** [comment] 2015-04-21 10:53
Well currently it has:

`re.sub('"|\'|<|>|\(|\)|\{|\}', '', paths)`

I just assumed it should be the same as [Line 150](https://github.com/titoBouzout/Open-Include/blob/555daefa/open_include.py#L150) which has:

`re.sub('"|\'|<|>|\(|\)|\{|\}|\[|\]|;', '', file_to_open)`

**Comment by titoBouzout** [comment] 2015-04-24 04:57
There was a regression in that expression, because we were unable to open file like this "Default (Windows).sublime-keymap" Now fixed and expression updated to match the other one (As appending)

**Closed by titoBouzout** 2015-04-24 04:57 UTC

**Comment by xHN35RQ** [comment] 2015-04-24 08:51
Thanks!
